version = 2
imports = ["/usr/share/containerd/config.toml"]

[plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.k8s.io"]
endpoint = ["https://10.0.2.2:5000"]

[plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
endpoint = ["https://10.0.2.2:5000"]
