services:
  aranet4-exporter:
    build: .
    image: aranet4-exporter
    container_name: aranet4-exporter
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - ./.devices.cfg:/devices.cfg
    command: /bin/sh -x -c "/aranet4-exporter -interval ${SCRAPE_INTERVAL_SEC} $(cat /devices.cfg)"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: aranet4-prometheus
    user: "${UID}"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=2w'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - ${METRICS_PORT}:9090

  grafana:
    image: grafana/grafana:11.4.0
    user: "${UID}"
    volumes:
      - ./dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
      - ./dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana-data:/var/lib/grafana
    environment:
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/dashboard.json
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_DEFAULT_THEME=light
    restart: unless-stopped
    ports:
      - ${DASHBOARD_PORT}:3000
