global:
  scrape_interval:     1m
  evaluation_interval: 1m

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'aranet'
    scrape_interval: 1m 
    static_configs:
      - targets: ['aranet4-exporter:9963']
