#!/bin/bash

script=$(realpath -e "$1")
cd "${script%/*}" || exit 1

function print_line() {
  printf "\033[1;36m\$\033[0m \033[1;32m%s\033[0m " "${line%% \{,\}*}"
}

trap 'printf "\n"; print_line' CONT

while IFS= read -r line; do
  if [[ -z ${line} || ${line} == "#"* ]]; then
    continue
  elif [[ ${line} == "{,}"* ]]; then
    eval "${line}" < /dev/tty
  else
    while true; do
      printf "\n"
      print_line
      read input < /dev/tty
      [[ ${input} == r ]] || break
      printf "\033[1A\033[2K"
      line=${oldline} print_line
      printf "\n"
      eval "${oldline}" < /dev/tty
    done
    eval "${line}" < /dev/tty
  fi
  oldline=${line}
done < "${script}"
